### ISSUE TITLE
Moving skull items in inventory causes items to be dropped on the ground

### ISSUE THREAD

**Issue by Danilado** [nea89o/Firmament#57]
How to reproduce:

1. Install Minecraft 1.21.4
2. Move skull item in inventory without firmament (not shift-clicking, sometimes you have to move them a couple of times). Everything should move just fine
3. Install firmament
4. Move skull item in inventory with firmament (not shift-clicking, sometimes you have to move them a couple of times)
5. Observe item being thrown on the ground

* Skull items refer to any items that are rendered as custom skulls in vanilla (e.g., runes, gemstone gauntlet, equipment, XP bottles).

** Sometimes this also happens with enchanted books, but it seems to occur in vanilla as well.

*** The issue occurs both with and without resource packs.

**Comment by Danilado** [comment]
Important details

This problem was fixed by Hypixel in Vanilla 1.21.4 (so Vanilla 1.21 -- 1.21.3 is still buggy)

However it seems that Firmament reintroduces it

**Comment by nea89o** [comment]
Hi, which version of Firmament are you using? I fixed an item desync issue a couple of days ago.

**Comment by justino901** [comment]
its happening to me on latest version. Do you think its because of old config files?

**Comment by Danilado** [comment]
I was mostly reporting this on behalf of justino.
I faced the problem on older versions of firmament but couldn't test the new one (Im banned for 30 days for a dumb reason)

**Comment by justino901** [comment]
not a old config files issue as i tried deleting them and the issue persists

**Comment by nea89o** [comment]
> its happening to me on latest version.

latest is not a version number. Please give me a version number.

**Comment by justino901** [comment]
Was happening to me on version Firmament 2.2.0+mc1.21.4 and Firmament 2.3.0+mc1.21.4 when I downloaded it this morning for the cake slices

**Comment by nea89o** [comment]
Could potentially be fixed with https://github.com/nea89o/Firmament/commit/a183a48bf0a5645acff10ebcc90ab10397ced283 ? Can't really confirm since it is really inconsistent if the bug happens for me.

**Comment by justino901** [comment]
I'll check myself once I'm home which should be in about 1 hour

**Comment by justino901** [comment]
> Could potentially be fixed with [a183a48](https://github.com/nea89o/Firmament/commit/a183a48bf0a5645acff10ebcc90ab10397ced283) ? Can't really confirm since it is really inconsistent if the bug happens for me.

can also confirm that this fixes the the desync head dropping issue
